spring:
  profiles.default: default
---

spring:
  profiles: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    jdbc-url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    username: securityadv
    password: 
    hikari:
      jdbc-url:  jdbc:postgresql://db.midnightbsd.org/security-advisory
      maximum-pool-size: 10
      minimum-idle: 2
  flyway:
    baseline-on-migrate: true
    user: securityadv
    password: 
    url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    table: schema_version
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      use-new-id-generator-mappings: false
    generate-ddl: false
    show-sql: false
    properties:
     hibernate:
       temp:
         use_jdbc_metadata_defaults: false
     javax:
       persistence:
         sharedCache:
           mode: ALL
  cache:
    type: REDIS
  redis:
    host: localhost
    port: 6379
    database: 0
  data:
    jest:
      uri: http://localhost:9200
      aws-region: us-east-1

eureka:
  client:
    serviceUrl:
     defaultZone: http://eureka.justjournal.com:8761/eureka/

server:
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

nvdfeed:
  baseUrl:  https://static.nvd.nist.gov/feeds/json/cve/1.0/
  baseUrl2: http://people.midnightbsd.org/~laffer1/advisory/

search:
  nvd-item-index: nvditem



---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost/security_advisory_test
    username: postgres
    password:
  flyway:
    baseline-on-migrate: true

---
spring:
  profiles: prod
  redis:
    host: midnightbsd-redis.c6ifkh.0001.use1.cache.amazonaws.com
    port: 6379
    database: 1
  data:
    jest:
      uri: http://vpc-mnbsd-3en4agwhc4ud7wmwuigo7aovwi.us-east-1.es.amazonaws.com
      aws-region: us-east-1
  flyway:
    url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      maximum-pool-size: 10
      minimum-idle: 2
    url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    jdbc-url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: securityadv
    password: mnbsdapp
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: US_EAST_1

eureka:
  client:
    serviceUrl:
      defaultZone: http://appstore.midnightbsd.org:8761/eureka/
