spring:
  profiles.default: default
---

spring:
  config:
    activate:
      on-profile: default
  jackson:
    serialization:
      write-dates-as-timestamps: false
  datasource:
    url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    jdbc-url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    username: securityadv
    password: 
    hikari:
      jdbc-url:  jdbc:postgresql://db.midnightbsd.org/security-advisory
      maximum-pool-size: 10
      minimum-idle: 2
  flyway:
    baseline-on-migrate: true
    user: securityadv
    password: 
    url: jdbc:postgresql://db.midnightbsd.org/security-advisory
    table: schema_version
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    generate-ddl: false
    show-sql: false
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        jdbc:
          lob:
            non_contextual_creation
      jakarta:
        persistence:
          sharedCache:
            mode: ALL
  elasticsearch:
    uris: http://localhost:9200

server:
  port: 8210
  tomcat:
    remote_ip_header: x-forwarded-for
    protocol_header: x-forwarded-proto

nvdfeed:
  serviceUrl: https://services.nvd.nist.gov/rest/json/
  apiKey:

search:
  nvd-item-index: nvditem

logging:
  level:
    root: info
    org.springframework.web: warn
    org.hibernate: error

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:postgresql://localhost/security_advisory_test
    username: postgres
    password:
  flyway:
    baseline-on-migrate: true

---
spring:
  config:
    activate:
      on-profile: prod
  elasticsearch:
    uris:
  flyway:
    url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
      maximum-pool-size: 10
      minimum-idle: 2
    url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    jdbc-url: jdbc:postgresql://security-advisory.c9or38nglwhm.us-east-1.rds.amazonaws.com/advisory?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    username: securityadv
    password:
cloud:
  aws:
    credentials:
      accessKey:
      secretKey:
    region:
      static: US_EAST_1

